name: Publish Package to NPM registry

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: yarn
      - name: Check lint errors
        run: yarn lint
      - name: Run unit tests
        run: yarn test
      - name: Run e2e tests
        run: yarn test:e2e
      - name: Generate index files
        run: yarn generate:index
      - name: Build application
        run: yarn build
      - name: Publish to registry
        if: startsWith(github.ref, 'refs/tags')
        run: |
          git config --local user.email "${{ github.event.head_commit.author.email }}"
          git config --local user.name "${{ github.event.head_commit.author.name }}"
          yarn publish --new-version '${{ github.ref_name }}'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
